/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_user_myapplication_Camera */

#ifndef _Included_com_example_user_myapplication_Camera
#define _Included_com_example_user_myapplication_Camera
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_user_myapplication_Camera_PERMISSIONS_REQUEST_CODE
#define com_example_user_myapplication_Camera_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     com_example_user_myapplication_Camera
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_user_myapplication_Camera_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
