/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_user_myapplication_MainActivity */

#ifndef _Included_com_example_user_myapplication_MainActivity
#define _Included_com_example_user_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_user_myapplication_MainActivity
 * Method:    cvGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_user_myapplication_MainActivity_cvGray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_example_user_myapplication_MainActivity
 * Method:    detectFace
 * Signature: (Ljava/lang/String;JJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_user_myapplication_MainActivity_detectFace
  (JNIEnv *, jobject, jstring, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
